// Generated by gencpp from file my_service/AddIntsRequest.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ADDINTSREQUEST_H
#define MY_SERVICE_MESSAGE_ADDINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct AddIntsRequest_
{
  typedef AddIntsRequest_<ContainerAllocator> Type;

  AddIntsRequest_()
    : matrix()  {
    }
  AddIntsRequest_(const ContainerAllocator& _alloc)
    : matrix(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int64_t>> _matrix_type;
  _matrix_type matrix;





  typedef boost::shared_ptr< ::my_service::AddIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::AddIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddIntsRequest_

typedef ::my_service::AddIntsRequest_<std::allocator<void> > AddIntsRequest;

typedef boost::shared_ptr< ::my_service::AddIntsRequest > AddIntsRequestPtr;
typedef boost::shared_ptr< ::my_service::AddIntsRequest const> AddIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::AddIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::AddIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::AddIntsRequest_<ContainerAllocator1> & lhs, const ::my_service::AddIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.matrix == rhs.matrix;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::AddIntsRequest_<ContainerAllocator1> & lhs, const ::my_service::AddIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97a0476db3c371263201aae690d8d4a7";
  }

  static const char* value(const ::my_service::AddIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97a0476db3c37126ULL;
  static const uint64_t static_value2 = 0x3201aae690d8d4a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/AddIntsRequest";
  }

  static const char* value(const ::my_service::AddIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] matrix\n"
;
  }

  static const char* value(const ::my_service::AddIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::AddIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::AddIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::AddIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "matrix[]" << std::endl;
    for (size_t i = 0; i < v.matrix.size(); ++i)
    {
      s << indent << "  matrix[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.matrix[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ADDINTSREQUEST_H
