// Generated by gencpp from file my_service/AddIntsResponse.msg
// DO NOT EDIT!


#ifndef MY_SERVICE_MESSAGE_ADDINTSRESPONSE_H
#define MY_SERVICE_MESSAGE_ADDINTSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_service
{
template <class ContainerAllocator>
struct AddIntsResponse_
{
  typedef AddIntsResponse_<ContainerAllocator> Type;

  AddIntsResponse_()
    : determinant(0)  {
    }
  AddIntsResponse_(const ContainerAllocator& _alloc)
    : determinant(0)  {
  (void)_alloc;
    }



   typedef int64_t _determinant_type;
  _determinant_type determinant;





  typedef boost::shared_ptr< ::my_service::AddIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_service::AddIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddIntsResponse_

typedef ::my_service::AddIntsResponse_<std::allocator<void> > AddIntsResponse;

typedef boost::shared_ptr< ::my_service::AddIntsResponse > AddIntsResponsePtr;
typedef boost::shared_ptr< ::my_service::AddIntsResponse const> AddIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_service::AddIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_service::AddIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_service::AddIntsResponse_<ContainerAllocator1> & lhs, const ::my_service::AddIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.determinant == rhs.determinant;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_service::AddIntsResponse_<ContainerAllocator1> & lhs, const ::my_service::AddIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_service::AddIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_service::AddIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_service::AddIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32ab7b72f712f20196be2866cf140ce9";
  }

  static const char* value(const ::my_service::AddIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32ab7b72f712f201ULL;
  static const uint64_t static_value2 = 0x96be2866cf140ce9ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_service/AddIntsResponse";
  }

  static const char* value(const ::my_service::AddIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 determinant\n"
;
  }

  static const char* value(const ::my_service::AddIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_service::AddIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.determinant);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_service::AddIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_service::AddIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "determinant: ";
    Printer<int64_t>::stream(s, indent + "  ", v.determinant);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_SERVICE_MESSAGE_ADDINTSRESPONSE_H
